# Site settings
title: Chris Amanse
header-img: img/home-bg.jpg
email: christopheramanse@gmail.com
description: "Thoughts, guides, and tips on iOS development, and related software and technology."
baseurl: ""
url: "http://www.chrisamanse.me"
twitter_username: ChrisAmanse
github_username:  chrisamanse
facebook_username:  chrisamanse

disqus_enabled: true
google_analytics_enabled: true

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 6
paginate_path: /:num/
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "LICENSE-Clean-Blog", "README-Clean-Blog.md"]
